title: Vidhi Agrawal
description: Digital Journey Specialist · IDFC First Bank
url: "https://vidhiagrawal.in"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
